<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.XlGHNoY.phpDocumentor\Reflection\Types\Integer' shared service.

$this->throw('Cannot autowire service ".service_locator.XlGHNoY": it references class "phpDocumentor\\Reflection\\Types\\Integer" but no such service exists.');
