<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liform.guesser.validator' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeGuesserInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Validator/ValidatorTypeGuesser.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Guesser/ValidatorGuesser.php';

return $this->services['liform.guesser.validator'] = new \Limenius\Liform\Guesser\ValidatorGuesser(($this->services['validator'] ?? $this->load('getValidatorService.php')));
