<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ptfT9k2' shared service.

return $this->privates['.service_locator.ptfT9k2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userProvider' => ['privates', 'security.user.provider.concrete.app_user_provider', 'getSecurity_User_Provider_Concrete_AppUserProviderService.php', true],
], [
    'userProvider' => '?',
]);
