<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZkG0hno' shared service.

return $this->privates['.service_locator.ZkG0hno'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'exception' => ['privates', '.errored..service_locator.ZkG0hno.Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException', NULL, 'Cannot autowire service ".service_locator.ZkG0hno": it references class "Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException" but no such service exists.'],
], [
    'exception' => 'Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException',
]);
