<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cdXswCz' shared service.

return $this->privates['.service_locator.cdXswCz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'apiService' => ['services', 'App\\Services\\MajPanel\\ApiService', 'getApiServiceService.php', true],
    'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'jWTTokenManagerInterface' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService.php', true],
    'jwtService' => ['privates', 'App\\Services\\MajPanel\\JwtService', 'getJwtServiceService.php', true],
], [
    'apiService' => 'App\\Services\\MajPanel\\ApiService',
    'encoder' => '?',
    'jWTTokenManagerInterface' => '?',
    'jwtService' => 'App\\Services\\MajPanel\\JwtService',
]);
