<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Am53qdV' shared service.

return $this->privates['.service_locator.Am53qdV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authenticationUtils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
    'jWTTokenManagerInterface' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService.php', true],
    'jwtService' => ['privates', 'App\\Services\\MajPanel\\JwtService', 'getJwtServiceService.php', true],
], [
    'authenticationUtils' => '?',
    'jWTTokenManagerInterface' => '?',
    'jwtService' => 'App\\Services\\MajPanel\\JwtService',
]);
