<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XlGHNoY' shared service.

return $this->privates['.service_locator.XlGHNoY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'id' => ['privates', '.errored..service_locator.XlGHNoY.phpDocumentor\\Reflection\\Types\\Integer', NULL, 'Cannot autowire service ".service_locator.XlGHNoY": it references class "phpDocumentor\\Reflection\\Types\\Integer" but no such service exists.'],
], [
    'id' => 'phpDocumentor\\Reflection\\Types\\Integer',
]);
