<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liform.resolver' shared service.

include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/ResolverInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Resolver.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/TransformerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/AbstractTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/IntegerTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/ArrayTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/CompoundTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/ChoiceTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/StringTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/NumberTransformer.php';
include_once \dirname(__DIR__, 4).'/vendor/limenius/liform/src/Limenius/Liform/Transformer/BooleanTransformer.php';

$this->services['liform.resolver'] = $instance = new \Limenius\Liform\Resolver();

$a = ($this->services['translator'] ?? $this->load('getTranslatorService.php'));
$b = ($this->services['liform.guesser.validator'] ?? $this->load('getLiform_Guesser_ValidatorService.php'));

$instance->setTransformer('integer', new \Limenius\Liform\Transformer\IntegerTransformer($a, $b), NULL);
$instance->setTransformer('collection', new \Limenius\Liform\Transformer\ArrayTransformer($a, $b, $instance), NULL);
$instance->setTransformer('compound', new \Limenius\Liform\Transformer\CompoundTransformer($a, $b, $instance), NULL);
$instance->setTransformer('choice', new \Limenius\Liform\Transformer\ChoiceTransformer($a, $b), NULL);
$instance->setTransformer('text', new \Limenius\Liform\Transformer\StringTransformer($a, $b), NULL);
$instance->setTransformer('url', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'url');
$instance->setTransformer('search', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'search');
$instance->setTransformer('money', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'money');
$instance->setTransformer('password', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'password');
$instance->setTransformer('textarea', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'textarea');
$instance->setTransformer('time', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'time');
$instance->setTransformer('percent', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'percent');
$instance->setTransformer('email', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'email');
$instance->setTransformer('date', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'date');
$instance->setTransformer('datetime', new \Limenius\Liform\Transformer\StringTransformer($a, $b), 'datetime');
$instance->setTransformer('number', new \Limenius\Liform\Transformer\NumberTransformer($a, $b), NULL);
$instance->setTransformer('checkbox', new \Limenius\Liform\Transformer\BooleanTransformer($a, $b), 'checkbox');

return $instance;
