<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.XXMbYmx.Symfony\Component\Security\Core\Authentication\Token\TokenInterface' shared service.

$this->throw('Cannot autowire service ".service_locator.XXMbYmx": it references interface "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface" but no such service exists. Did you create a class that implements this interface?');
