<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8g7Ch4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8g7Ch4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8g7Ch4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8g7Ch4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU8g7Ch4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U8g7Ch4',
    'container.build_id' => '8a4125c8',
    'container.build_time' => 1603534055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8g7Ch4');
